FROM oven/bun:1.2.19 AS builder

WORKDIR /build

COPY package.json bun.lock turbo.json ./
COPY packages/db ./packages/db

COPY apps/api ./apps/api

WORKDIR /build/apps/api
RUN bun install 
RUN bun run build 

FROM oven/bun:1.2.19 AS runtime 
WORKDIR /app 

COPY --from=builder /build/apps/api/dist ./dist
COPY --from=builder /build/apps/api/package.json ./package.json
COPY --from=builder /build/node_modules ./node_modules 
COPY --from=builder /build/bun.lock ./bun.lock

ENV NODE_ENV=production 
ENV PORT=8080 
EXPOSE 8080

CMD ["bun", "run", "start"]